version: "3.8"
services:
  # Frontend - React service
  frontend:
    build:
      context: ./frontend
    # tty: true
    volumes:
      - ./frontend:/frontend
      - nextjs-node-modules:/frontend/node_modules
    ports:
      - "3000:3000"
    networks:
      - ft_transcendence
  
  # Backend - NestJS service
  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/backend
      - nestjs-node-modules:/backend/node_modules
    ports:
      - "3001:3000"
    networks:
      - ft_transcendence
    depends_on:
      - database

  # Database - PostgreSQL service
  database:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ts_user
      POSTGRES_PASSWORD: ts_password
      POSTGRES_DB: ts_database
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - ft_transcendence

networks:
  ft_transcendence:
    driver: bridge

volumes:
  pgdata:
  nestjs-node-modules:
  nextjs-node-modules: